version: '3'
services:
  oauth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: oauth_mhaa
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

