version: '3'
services:

  auth-db:
    image: postgres:14.12
    networks:
      - hmpps
    container_name: auth-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth-db

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    container_name: auth_mhaa
    networks:
      - hmpps
    ports:
      - '9090:8080'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/auth/health']
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis,local-postgres
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth-db

  manage-users-api:
    image: quay.io/hmpps/hmpps-manage-users-api:latest
    networks:
      - hmpps
    container_name: manage-users-api_mhaa
    depends_on:
      - hmpps-auth
    ports:
      - "9091:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_AUTH_ENDPOINT_URL=http://hmpps-auth:8080/auth
      - EXTERNAL_USERS_ENDPOINT_URL=http://hmpps-external-users-api:8080

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth


  hmpps-external-users-api:
    image: quay.io/hmpps/hmpps-external-users-api:latest
    networks:
      - hmpps
    container_name: hmpps-external-users-api
    depends_on:
      - hmpps-auth
    ports:
      - "8083:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev,local-postgres
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth
      - SPRING_R2DBC_URL=r2dbc:postgresql://auth-db:5432/auth-db?sslmode=prefer
      - SPRING_FLYWAY_URL=jdbc:postgresql://auth-db:5432/auth-db?sslmode=prefer

  hmpps-audit-api:
    image: quay.io/hmpps/hmpps-audit-api:latest
    container_name: hmpps-audit-api
    networks:
      - hmpps
    depends_on:
      - audit-db
    ports:
      - "8084:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,localstack

  audit-db:
    image: postgres
    networks:
      - hmpps
    container_name: audit-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=audit-db

  localstack:
    image: localstack/localstack:2.0
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - 8999:8080
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
