export const SET_CONFIG = 'SET_CONFIG'

export const SET_USER_DETAILS = 'SET_USER_DETAILS'

export const SET_ERROR = 'SET_ERROR'
export const RESET_ERROR = 'RESET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_LOADED = 'SET_LOADED'

export const SET_USER_SEARCH_NAME_FILTER = 'SET_USER_SEARCH_NAME_FILTER'
export const SET_USER_SEARCH_ROLE_FILTER = 'SET_USER_SEARCH_ROLE_FILTER'
export const SET_USER_SEARCH_ROLE_ADD = 'SET_USER_SEARCH_ROLE_ADD'
export const SET_USER_SEARCH_RESULTS_LIST = 'SET_USER_SEARCH_RESULTS_LIST'
export const SET_USER_SEARCH_ROLE_FILTER_LIST = 'SET_USER_SEARCH_ROLE_FILTER_LIST'
export const SET_USER_SEARCH_ROLE_LIST = 'SET_USER_SEARCH_ROLE_LIST'
export const SET_USER_SEARCH_CONTEXT_USER = 'SET_USER_SEARCH_CONTEXT_USER'
export const SET_USER_SEARCH_PAGINATION_PAGE_SIZE = 'SET_USER_SEARCH_PAGINATION_PAGE_SIZE'
export const SET_USER_SEARCH_PAGINATION_PAGE_NUMBER = 'SET_USER_SEARCH_PAGINATION_PAGE_NUMBER'
export const SET_USER_SEARCH_PAGINATION_TOTAL_RECORDS = 'SET_USER_SEARCH_PAGINATION_TOTAL_RECORDS'

export const SET_AUTH_USER_SEARCH_RESULTS_LIST = 'SET_AUTH_USER_SEARCH_RESULTS_LIST'
export const SET_AUTH_USER_ROLE_LIST = 'SET_AUTH_USER_ROLE_LIST'
export const SET_AUTH_USER_GROUP_LIST = 'SET_AUTH_USER_GROUP_LIST'
export const SET_AUTH_USER_CONTEXT_USER = 'SET_AUTH_USER_CONTEXT_USER'

export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR'
export const RESET_VALIDATION_ERRORS = 'RESET_VALIDATION_ERRORS'

export const SET_MENU_OPEN = 'SET_MENU_OPEN'

export const SET_PRISON_LEVEL_KEY_WORKER_STATS = 'SET_PRISON_LEVEL_KEY_WORKER_STATS'
