// eslint-disable-next-line no-shadow,import/prefer-default-export
export enum ManageUsersEvent {
  VIEW_GROUP_DETAILS_ATTEMPT = 'VIEW_GROUP_DETAILS_ATTEMPT',
  VIEW_GROUP_DETAILS_FAILURE = 'VIEW_GROUP_DETAILS_FAILURE',
  VIEW_USER_ATTEMPT = 'VIEW_USER_ATTEMPT',
  VIEW_USER_FAILURE = 'VIEW_USER_FAILURE',
  REMOVE_USER_ROLE_ATTEMPT = 'REMOVE_USER_ROLE_ATTEMPT',
  REMOVE_USER_ROLE_FAILURE = 'REMOVE_USER_ROLE_FAILURE',
  CREATE_EMAIL_DOMAIN_ATTEMPT = 'CREATE_EMAIL_DOMAIN_ATTEMPT',
  CREATE_EMAIL_DOMAIN_FAILURE = 'CREATE_EMAIL_DOMAIN_FAILURE',
  CREATE_GROUP_ATTEMPT = 'CREATE_GROUP_ATTEMPT',
  CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE',
  VIEW_USER_GROUPS_ATTEMPT = 'VIEW_USER_GROUPS_ATTEMPT',
}
