version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7.1.0
  browser-tools: circleci/browser-tools@1.4.1
  slack: circleci/slack@4.12.1

parameters:
  alerts-slack-channel:
    type: string
    default: hmpps_tech_alerts_security

  releases-slack-channel:
    type: string
    default: dps-releases

  node-version:
    type: string
    default: 18.12-browsers

jobs:
  build:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: CYPRESS_INSTALL_BINARY=0 npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run Tests
          command: |
            set -e
            npm test -- --maxWorkers=2
      - run: NODE_ENV=production npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - dist
            - .cache/Cypress

  integration_tests:
    working_directory: ~/app
    executor:
      name: hmpps/node_redis
      node_tag: << pipeline.parameters.node-version >>
      redis_tag: "6.2"
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Get wiremock
          command: curl -o wiremock.jar https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2/wiremock-standalone-2.27.2.jar
      - run:
          name: Run auth wiremock
          command: java -jar wiremock.jar --port 9191
          background: true
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install cypress.
          command: npx cypress install
      - run:
          name: Run the node app.
          command: npm run start-feature
          background: true
      - run:
          name: integration tests
          command: npm run int-test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: integration-tests/videos
      - store_artifacts:
          path: integration-tests/screenshots

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build_docker
            - integration_tests
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          context:
            - hmpps-common-vars
            - hmpps-manage-users-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          context:
            - hmpps-common-vars
            - hmpps-manage-users-prod
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "7 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_outdated:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/npm_security_audit:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "59 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
