version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.1.0

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 14-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: CYPRESS_INSTALL_BINARY=0 npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run Tests
          command: |
            set -e
            npm test -- --maxWorkers=2
      - run: NODE_ENV=production npm run build
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - dist

  integration_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:14-buster-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run the node app.
          command: npm run start-feature --env=feature.env
          background: true
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "manage-accounts-specs/build.gradle" }}
      - run:
          name: Run Integration Tests
          command: ./gradlew check
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "manage-accounts-specs/build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_artifacts:
          path: manage-accounts-specs/build/reports
          destination: integration/spock
      - store_artifacts:
          path: manage-accounts-specs/build/geb-reports
          destination: integration/geb
      - store_test_results:
          path: manage-accounts-specs/build/test-results

  cypress_integration_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:14-buster-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Get wiremock
          command: curl -o wiremock.jar https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.27.2/wiremock-standalone-2.27.2.jar
      - run:
          name: Run auth wiremock
          command: java -jar wiremock.jar --port 9191
          background: true
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install cypress.
          command: npx cypress install
      - run:
          name: Run the node app.
          command: npm run start-feature --env=cypress.env
          background: true
      - run:
          name: integration tests
          command: npm run int-test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: integration-tests/videos
      - store_artifacts:
          path: integration-tests/screenshots

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - build
      - cypress_integration_tests:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build_docker
            - integration_tests
            - cypress_integration_tests
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: manage-hmpps-auth-accounts-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: manage-hmpps-auth-accounts-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: '0 7 * * 1-5'
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit
