version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@1.0.0

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 12-buster-browsers
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run Tests
          command: |
            set -e
            npm test -- --maxWorkers=2
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  integration_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:12-buster-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run the node app.
          command: npm run start-feature-no-webpack --env=feature.env
          background: true
      - restore_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: gradle-cache-{{ checksum "manage-accounts-specs/build.gradle" }}
      - run:
          name: Run Integration Tests
          command: ./gradlew build
      - save_cache:
          key: gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - /home/circleci/.gradle/wrapper
      - save_cache:
          key: gradle-cache-{{ checksum "manage-accounts-specs/build.gradle" }}
          paths:
            - /home/circleci/.gradle/caches
      - store_artifacts:
          path: manage-accounts-specs/build/reports
          destination: integration/spock
      - store_artifacts:
          path: manage-accounts-specs/build/geb-reports
          destination: integration/geb
      - store_test_results:
          path: manage-accounts-specs/build/test-results

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - integration_tests:
          requires:
            - build
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - integration_tests
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: manage-hmpps-auth-accounts-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: manage-hmpps-auth-accounts-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: '0 7 * * 1-5'
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit
