---
# Values here are the same across all environments

generic-service:
  nameOverride: hmpps-manage-users

  image:
    repository: quay.io/hmpps/hmpps-manage-users
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      # note this limit is per ingress replica
      nginx.ingress.kubernetes.io/limit-rpm: "120"
      # setting to 429 (default is 503) so we can alert on this
      nginx.ingress.kubernetes.io/server-snippet: |
        add_header X-Robots-Tag "noindex, nofollow";
        limit_req_status 429;
    tlsSecretName: hmpps-manage-users-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      {{ if .Values.ingress.modsecurity_audit_enabled -}}
      SecAuditEngine RelevantOnly
      SecAuditLog /var/log/nginx/error.log
      SecAuditLogType Serial
      {{ end -}}
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateTargetById 942100 "!ARGS"  # disable libinjection testing on request args. to disable all SQLi testing, modify rules in the range 942100-942999
      SecAction \
        "id:900000,\
         phase:1,\
         nolog,\
         pass,\
         t:none,\
         setvar:tx.paranoia_level=2"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  env:
    NODE_ENV: production
    TOKENVERIFICATION_API_ENABLED: true
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    NOMIS_USERS_API_ENDPOINT_TIMEOUT_SECONDS: "120"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-manage-users:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      GOOGLE_TAG_MANAGER_ID: "GOOGLE_TAG_MANAGER_ID"
      SESSION_COOKIE_SECRET: "SESSION_COOKIE_SECRET"
    hmpps-redis:
      REDIS_HOST: "REDIS_HOST"
      REDIS_PASSWORD: "REDIS_PASSWORD"

generic-prometheus-alerts:
  targetApplication: hmpps-manage-users
