---
# Environment specific values, override helm_deploy/hmpps-manage-users/values.yaml

generic-service:
  replicaCount: 4
  ingress:
    host: manage-users-preprod.hmpps.service.justice.gov.uk

  env:
    API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
    MANAGE_USERS_API_ENDPOINT_URL: https://hmpps-manage-users-api-preprod.hmpps.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    DPS_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk
    HMPPS_COOKIE_NAME: hmpps-session-preprod
    NODE_ENV: production
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    TOKENVERIFICATION_API_ENABLED: true
    SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk
    SYSTEM_PHASE: PRE-PRODUCTION
    FEATURE_DPS_USER_FILTER_SEARCH: false
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
