# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/manage-hmpps-auth-accounts
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  class: modsec01
  modsecurity_enabled: true
  host: manage-hmpps-auth-accounts-preprod.prison.service.justice.gov.uk
  cert_secret: manage-hmpps-auth-accounts-cert
  path: /

env:
  API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
  NN_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk/
  DPS_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk
  HMPPS_COOKIE_NAME: hmpps-session-preprod
  NODE_ENV: production
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk
  SYSTEM_PHASE: PRE-PRODUCTION

