---
# Environment specific values, override helm_deploy/hmpps-manage-users/values.yaml

generic-service:
  ingress:
    host: manage-users-preprod.hmpps.service.justice.gov.uk

  env:
    MANAGE_USERS_API_ENDPOINT_URL: https://manage-users-api-preprod.hmpps.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    DPS_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk
    NOMIS_USERS_API_ENDPOINT_URL: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk
    HMPPS_COOKIE_NAME: hmpps-session-preprod
    HMPPS_COOKIE_DOMAIN: manage-users-preprod.hmpps.service.justice.gov.uk
    MANAGE_HMPPS_USERS_URL: https://manage-users-preprod.hmpps.service.justice.gov.uk
    TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
    SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk
    SYSTEM_PHASE: PRE-PRODUCTION

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
