# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: quay.io/hmpps/hmpps-manage-users
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  class: modsec01
  modsecurity_enabled: true
  host: hmpps-manage-users-preprod.prison.service.justice.gov.uk
  cert_secret: hmpps-manage-users-cert
  path: /

env:
  API_ENDPOINT_URL: https://api-preprod.prison.service.justice.gov.uk
  MANAGE_USERS_API_ENDPOINT_URL: https://hmpps-manage-users-api-preprod.hmpps.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
  DPS_ENDPOINT_URL: https://digital-preprod.prison.service.justice.gov.uk
  HMPPS_COOKIE_NAME: hmpps-session-preprod
  NODE_ENV: production
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  TOKENVERIFICATION_API_URL: https://token-verification-api-preprod.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true
  SUPPORT_URL: https://support-preprod.hmpps.service.justice.gov.uk
  SYSTEM_PHASE: PRE-PRODUCTION
  FEATURE_DPS_USER_FILTER_SEARCH: false


# CloudPlatform AlertManager receiver to route promethues alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
