# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: quay.io/hmpps/manage-hmpps-auth-accounts
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  modsecurity_audit_enabled: true
  host: manage-hmpps-auth-accounts-dev.prison.service.justice.gov.uk
  cert_secret: manage-hmpps-auth-accounts-cert
  path: /

env:
  API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk
  OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  NN_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk/
  DPS_ENDPOINT_URL: https://whereabouts-dev.prison.service.justice.gov.uk
  HMPPS_COOKIE_NAME: hmpps-session-dev
  NODE_ENV: production
  WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
  TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
  TOKENVERIFICATION_API_ENABLED: true

