---
# Environment specific values, override helm_deploy/hmpps-manage-users/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: manage-users-dev.hmpps.service.justice.gov.uk
    modsecurity_audit_enabled: true

  env:
    API_ENDPOINT_URL: https://api-dev.prison.service.justice.gov.uk
    MANAGE_USERS_API_ENDPOINT_URL: https://hmpps-manage-users-api-dev.hmpps.service.justice.gov.uk
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    DPS_ENDPOINT_URL: https://digital-dev.prison.service.justice.gov.uk
    HMPPS_COOKIE_NAME: hmpps-session-dev
    NODE_ENV: production
    WEB_SESSION_TIMEOUT_IN_MINUTES: "60"
    TOKENVERIFICATION_API_URL: https://token-verification-api-dev.prison.service.justice.gov.uk
    TOKENVERIFICATION_API_ENABLED: true
    SUPPORT_URL: https://support-dev.hmpps.service.justice.gov.uk
    SYSTEM_PHASE: DEV
    FEATURE_DPS_USER_FILTER_SEARCH: true
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
