---
# Per environment values which override defaults in hmpps-manage-users/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-users-stage.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: https://manage-users-stage.hmpps.service.justice.gov.uk
    HMPPS_AUTH_URL: https://sign-in-stage.hmpps.service.justice.gov.uk/auth
    DPS_ENDPOINT_URL: https://digital-stage.prison.service.justice.gov.uk
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-stage.prison.service.justice.gov.uk
    MANAGE_USERS_API_URL: https://manage-users-api-stage.hmpps.service.justice.gov.uk
    ENVIRONMENT_NAME: STAGE
    MANAGE_USER_ALLOW_LIST_ENABLED: true
    MANAGE_USER_ALLOW_LIST_ENVIRONMENT_LABEL: stage

generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
