---
# Environment specific values, override helm_deploy/hmpps-manage-users/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: manage-users-stage.hmpps.service.justice.gov.uk
    modsecurity_audit_enabled: true

  env:
    MANAGE_USERS_API_ENDPOINT_URL: https://manage-users-api-stage.hmpps.service.justice.gov.uk
    HMPPS_AUTH_URL: https://sign-in-stage.hmpps.service.justice.gov.uk/auth
    DPS_ENDPOINT_URL: https://digital-stage.prison.service.justice.gov.uk
    NOMIS_USERS_API_ENDPOINT_URL: https://nomis-user-roles-api-dev.prison.service.justice.gov.uk
    HMPPS_COOKIE_NAME: hmpps-session-stage
    HMPPS_COOKIE_DOMAIN: manage-users-stage.hmpps.service.justice.gov.uk
    MANAGE_HMPPS_USERS_URL: https://manage-users-stage.hmpps.service.justice.gov.uk
    TOKEN_VERIFICATION_API_URL: https://token-verification-api-stage.prison.service.justice.gov.uk
    SUPPORT_URL: https://support-stage.hmpps.service.justice.gov.uk
    SYSTEM_PHASE: STAGE

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
